### ISSUE TITLE
调整puppet-service中的日志级别

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet-service#152]
目前该项目中的日志级别极大部分都是`verbose`的，对于默认打印`info`级别日志的情况，排查某些问题会有不便。

如果将使用wechaty的默认日志等级调整为`verbose`会有很多冗余的`puppet-service`日志，影响日志的可读性。

因此需要将一些关键日志的等级做出调整。

**Comment by huan** [comment]
An internal module should never print messages to users because it should be "just works", and only print an error message when there's anything not expected.

The `PuppetService` is an internal module, so it should not print any message by default.
`log.info`

Just image that, for the TCP/IP OSI layers, if every layer prints log message to you, then it will be totally a mess.

**Comment by huan** [comment]
A better way to archive what you need, I believe is to add some events to the Brolog so that we can filter them.

For example:

```ts
log.on('verbose', (module, method, message) => {
  // filter module & method at here, and output whatever you want.
})
```

**Comment by huan** [comment]
Should be able to be solved by https://github.com/huan/brolog/issues/145

Stay tuned.
