### ISSUE TITLE
【wechaty问题交流微信群】一起讨论，吐槽，解决wechaty中遇到的坑

### ISSUE THREAD

**Issue by suxiaobei1024** [wechaty/wechaty-puppet-service#236]
![程序元阿维-个人微信-二维码](https://github.com/wechaty/puppet-service/assets/11757587/cc468bbd-7509-4ebd-985e-269925efac14)

加我的时候，麻烦备注: wechaty-xxxx

**Comment by huan** [comment]
@suxiaobei1024 Thanks for creating a community for Wechaty developers.

However, it should not be posted in Issues because this topic is unrelated to Issue.

Feel free to discuss at our Wechaty Discord Server at https://discord.gg/7q8NBZbQzt 

P.S. Duplicated with https://github.com/wechaty/wechaty/issues/2707
